### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by ShiZhengyan** [oriyor/ret-robust#1] opened 2023-10-06 21:32 UTC
Amazing work! May I kindly ask whether there is a plan to release the code?

Thanks,
Zhengxiang

**Comment by oriyor** [comment] 2023-10-07 02:09
Hi Zhengxiang,

Thanks for reaching out!

Of course all code will be made publicly available, but I'm now on some personal time off so it may take a few weeks. Is there a specific part you are more interested in?

**Comment by ShiZhengyan** [comment] 2023-10-08 21:16
It is fine. Have a nice holiday.

**Comment by kerkathy** [comment] 2023-12-08 06:27
Hi @oriyor 
This work is indeed outstanding! Since I'm also interested in this field, may I kindly ask the expected date of your code release? Thank you again.

**Comment by oriyor** [comment] 2023-12-12 10:57
> Hi @oriyor This work is indeed outstanding! Since I'm also interested in this field, may I kindly ask the expected date of your code release? Thank you again.

Hi @kerkathy, thanks for reaching out and for taking an interest in our work!
I think that around the end of December, but if there is a specific part you are interested it might already be available in other projects. What exactly are you interested in?

**Comment by kerkathy** [comment] 2024-01-08 09:11
Hi @oriyor ,
Since you mentioned that you were following the in-context RALMs from Ram et. al (2023), should I directly follow the code in https://github.com/AI21Labs/in-context-ralm ?
And actually I wanted to reproduce the work and play around a bit, so I'm curious about the few shot prompt and the hyperparamter in RALM you set to make it work. 
Also, if you can kindly share how you preprocess the data, that'll be even more great!

Thank you :)

**Comment by oriyor** [comment] 2024-01-14 14:32
Hi! I pushed the majority of the code. To run the NQ experiments, please see the [reasoning-on-cots](https://github.com/oriyor/reasoning-on-cots) project. Instructions on how to run experiments are [here](https://github.com/oriyor/reasoning-on-cots/tree/master/src/experiments/retrobust) and NQ prompts are [here](https://github.com/oriyor/reasoning-on-cots/blob/master/src/prompting/retrobust.py). I will add the remaining configs and prompts during the next few days. 

Please let me know if anything isn't working as expected :)

**Comment by kerkathy** [comment] 2024-01-14 16:55
@oriyor That's awesome, thank you!

**Comment by oriyor** [comment] 2024-01-21 21:01
Closing after the code release. Plz let me know if there are any additional issues.

**Closed as completed by oriyor** 2024-01-21 21:01 UTC
